version: '2'
services:
  develop:
    build: .
    container_name: datascience-notebook-development
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
